# Generated by Django 3.0.5 on 2020-04-03 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post',
            new_name='message',
        ),
    ]
